import { Inter } from 'next/font/google';
import { RootProvider } from './rootContext';
import Autocomplete from './components/search/searchBox';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div style={{ margin: '0 auto', padding: '20px' }}>
          <RootProvider>
            <div
              style={{
                width: '700px',
              }}
            >
              <Autocomplete />
            </div>
            {children}
          </RootProvider>
        </div>
      </body>
    </html>
  );
}
